version: '3.8'

services:
  backend:
    build: ./BackEndAPI
    ports:
      - "8000:8000"
    volumes:
      - ./BackEndAPI:/app
    command: uvicorn FastAPITest:app --host 0.0.0.0 --port 8000 --reload


  frontend:
    build: ./FrontEndVue
    ports:
      - "8080:8080"
    volumes:
      - ./FrontEndVue:/app
      - /app/node_modules
    command: npm run serve
    depends_on:
      - backend


